spring.application.name=proposal-management
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3307/proposals?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=app
spring.datasource.password=app
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver